### ISSUE TITLE
Two differents account can share the same wishlist

### ISSUE THREAD

**Issue by qlerebours** [BitBagCommerce/SyliusWishlistPlugin#12]
Steps to reproduce:
 - Log in with account1
 - Add products in wishlist
 - Logout
 - Log in with account2
 - Go to wishlist

Result: You have items in your account2's wishlist that account1 put in its wishlist.

I presume it should be due to local storage, but if users are logged in, the plugin shouldnt use local storage

**Comment by bitbager** [comment]
Fixed by @RadnoK. Thanks!

**Comment by qlerebours** [comment]
I will try it, thanks !

**Comment by qlerebours** [comment]
I tried it and sometimes it works sometimes not:
 - If I add product to wishlist from Account1, I logout, I create a new account (Account2), then on Account 2 I don't have items from Account1 in wishlist :heavy_check_mark: 
 - After the first test, I'm still logged as Account2, I add products to wishlist, i logout, i login with Account1, then Account1 has wishlist items from Account1 AND Account2 :x: 

Can you confirm that the last use case is working or not for you please ?

**Comment by bartektw** [comment]
Hi @qlerebours! This bug was removed in this commit: https://github.com/BitBagCommerce/SyliusWishlistPlugin/commit/0672dbaaa4fd0473ad4d93abf2702255672b46c4
