### ISSUE TITLE
The AddProductsToCartHandler does not check correctly for variant stock availability

### ISSUE THREAD

**Issue by lruozzi9** [BitBagCommerce/SyliusWishlistPlugin#127]
The AddProductsToCartHandler checks only if the variant is in stock, but this is not always sufficient. For this purpose, Sylius gives a service the AvailabilityCheckerInterface. This should be used in this handler instead of manual check for stock quantity.

**Comment by Wojdylak** [comment]
[#193 ](https://github.com/BitBagCommerce/SyliusWishlistPlugin/pull/193)

**Comment by Wojdylak** [comment]
Pull request merged
