### ISSUE TITLE
The AddProductsToCartHandler does not check if variant is selected

### ISSUE THREAD

**Issue by lruozzi9** [BitBagCommerce/SyliusWishlistPlugin#128]
The AddProductsToCartHandler will try to add to the cart all items, even if they are not selected. This will cause an error flash message because the quantities of not selected products can be empty.

**Comment by Wojdylak** [comment]
Yes, this will flash an error because AddProductsToCartHandler adds all products. AddSelectProductToCartHandler checks if variant is selected.
