### ISSUE TITLE
Huge performance problem and almost site-breaking

### ISSUE THREAD

**Issue by LucaGallinari** [BitBagCommerce/SyliusWishlistPlugin#130]
Hi guys,
there is a huge performance problem with the version 2.0.0 of this plugin. It's a combination of 2 changes that were made in this version and that were not properly addressed:

1. On EVERY first request of a "new user", a record is added to the btibag wishlist. [This is done here](https://github.com/BitBagCommerce/SyliusWishlistPlugin/blob/master/src/EventSubscriber/CreateNewWishlistSubscriber.php) with an event listener on the kernel request. As you can see, this logic check if the cookie "wishlist_cookie_token" is set, otherwise it creates a NEW WISHLIST record in the table. Maybe a normal user would navigate the website for sometime with that cookie properly set, but if we consider all the traffic coming from bots, that can easily ignore cookies, this will lead to a new record on the table for each request!
Moreover, there aren't any services that clean this table, so this will grow indefinitely.

2. The "unique" constraint on the token field in the wishlist bitbag plugin has been removed, and the only index of the table is on the "shop_user_id" (excluding the ID), but all queries are made by using the shop_user_id and the token, that is not indexed, resulting in a very slow query that reads all the records. Combined with the previous point, this leads to a slower and slower website: the table grows on each request and the wishlist is read on a huge table without proper indexes.

**Comment by Nek-** [comment]
⚠️ this is a critical issue, you should really look into 🙏 .

**Comment by HansTenBrinke** [comment]
I've just had to delete over a million unused entries in the wishlist table. The query to get the current wishlist was taking almost 2 seconds. Is there a reason to make the wishlist preemptively? Why not make one when the user interacts with it for the first time? This would prevent filling the database with garbage entries for users that have no interest in using a wishlist in the first place.

**Comment by Nek-** [comment]
Yes, this plugin should probably not be listed on sylius.com official plugins list considering how it's broken.

Just for your information, at Wishibam we forked the project and it is available here for those who want it: https://github.com/Wishibam/SyliusWishlistPlugin

However, there is no release manage management and maintenance promise yet.

**Comment by rafalmal** [comment]
We will fix this soon.

**Comment by oliver-schulz** [comment]
Maybe we are almost there because of the great work of @arek31 ?

https://github.com/BitBagCommerce/SyliusWishlistPlugin/pull/214

**Comment by nikkuexe** [comment]
This is a major issue.

**Comment by oliver-schulz** [comment]
@nikkuexe with the latest version it should be fixed -> v4.0.0. I did not manage to test this new version yet, but it looks very promising to me.

**Comment by nikkuexe** [comment]
Thanks @oliver-schulz 
We should probably look into also adding a cleaning command, similar to the [removal of expired carts command](https://github.com/Sylius/SyliusOrderBundle/blob/master/Command/RemoveExpiredCartsCommand.php).

**Comment by senghe** [comment]
Hi all! :) I've good news - the problem has been solved with [v4.0.2](https://github.com/BitBagCommerce/SyliusWishlistPlugin/releases/tag/v4.0.2) :tada:

The wishlist is now created only when you go to a wishlist context (`/wishlist` prefixed endpoints, or like on product page - when you need to display wishlists list).

Cheers! :)
