### ISSUE TITLE
Inconsistent wishlists for logged in user

### ISSUE THREAD

**Issue by LucaGallinari** [BitBagCommerce/SyliusWishlistPlugin#132]
With version 2.0, wishlists for logged in user have a lot of inconsistencies.

**Not logged in user**
The first time a user enter the website a new token is generated and assigned to the user. This token is stored both on DB and as cookie. The token is used as identifier to retrieve the wishlists of the user. If the user cleans his cookie the wishlist resets as a new token is generated and assigned to him. This is ok.

**The user logs in**
Now, if a not logged in user has a wishlist with some products and logs in, he will see the new wishlist as his token is still the same, but if he clean his cookies, the wishlist disappears. This is bad, and this is due to the fact that, on the DB, the field "shop_user_id" of the wishlist is not populated with the id of the user upon login.

Now, a new token has been generated, and the user can add products to the wishlist, and this wishlist has the "shop_user_id" populated. Ok, but now, everytime the user cleans his cookies a new token will be generated and a new wishlist will be created for him.

-----------

P.S. the demo [here](https://sylius-demo.bitbag.io/) doesn't seems to have the last version of this plugin. Moreover, it seems impossibile to register and login, cause the verification email is never delivered.

**Comment by Wojdylak** [comment]
Yes, it is a bug. I created PR #198

**Comment by Wojdylak** [comment]
Pull request merged
