### ISSUE TITLE
Error during cache generation

### ISSUE THREAD

**Issue by NeilPeyssard** [BitBagCommerce/SyliusWishlistPlugin#159]
**Sylius version:** 1.11.7
**Wishlist plugin version:** 2.0.5

Since the 2.0.5 version an error occurred when I run the cache:clear command with the `%kernel.debug%` set to `false` :

```
request.CRITICAL: Uncaught PHP Exception Error: "Failed opening required '/srv/sylius/var/cache/prod/doctrine/orm/Proxies/__CG__SyliusComponentChannelModelChannel.php' (include_path='.:/usr/local/lib/php')" at /srv/sylius/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php line 197 {"exception":"[object] (Error(code: 0): Failed opening required '/srv/sylius/var/cache/prod/doctrine/orm/Proxies/__CG__SyliusComponentChannelModelChannel.php' (include_path='.:/usr/local/lib/php') at /srv/sylius/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php:197)"}
```

Apparently the proxy class for `Sylius\Component\Channel\Model\Channel `cannot be generated. Actually we don't need a proxy class for the Sylius channel model, because we extend it as an entity.

After investigations it appears that the wishlist entity definition in the bitbag wishlist plugin is responsible for this error. The PR [#158](https://github.com/BitBagCommerce/SyliusWishlistPlugin/pull/158) will fix it.

**Comment by pbalcerzak** [comment]
Thank you for the PR, merged in v2.0.14
