### ISSUE TITLE
Add Sylius 1.12 support

### ISSUE THREAD

**Issue by valentin-harrang** [BitBagCommerce/SyliusWishlistPlugin#185]
Hi,

Do you plan to add compatibility with `Sylius 1.12`?

**Comment by senghe** [comment]
Hi, yes we are working on it currently :) I'll be back when have more details :)

**Comment by valentin-harrang** [comment]
Thank you :)

**Comment by senghe** [comment]
Hi, the Sylius 1.12 support is available from version [v3.0.0](https://github.com/BitBagCommerce/SyliusWishlistPlugin/releases/tag/v3.0.0) :tada:
