### ISSUE TITLE
upgrade to sylius 1.5/1.6

### ISSUE THREAD

**Issue by titi60** [BitBagCommerce/SyliusWishlistPlugin#20]
Hello,

I'm using this package and I recently wanted to upgrade to Sylius 1.6, but the package's dependancy to Sylius 1.4 make it impossible. It would be good to make a new tag for these new version au Sylius!

Thank you !

**Comment by damonsson** [comment]
Which version do you use?

**Comment by damonsson** [comment]
Works on 1.6.
