### ISSUE TITLE
Unknown column 'b0_.name' in 'field list' on fresh install

### ISSUE THREAD

**Issue by gponty** [BitBagCommerce/SyliusWishlistPlugin#202]
Hello,

I have this error message after install plugin (on sylius fresh install) :

An exception occurred while executing 'SELECT b0_.name AS name_0, b0_.token AS token_1, b0_.id AS id_2, b0_.shop_user_id AS shop_user_id_3, b0_.channel_id AS channel_id_4 FROM bitbag_wishlist b0_ WHERE b0_.shop_user_id = ? OR b0_.token = ? ORDER BY b0_.id ASC' with params [22, ""]:

Any idea ?
Thank you

**Comment by liszkapawel** [comment]
Hello @gponty,
I installed clean sylius and added wishlist to it and it works without a problems - probably your migration failed, try to update the database schema via `php bin/console doctrine:schema:update --force`
