### ISSUE TITLE
can't add to cart if stock not tracked

### ISSUE THREAD

**Issue by t-n-y** [BitBagCommerce/SyliusWishlistPlugin#207]
Hi,

I was wondering is there is a reason why you don't take into account if the product stock is tracked or not. 
If the product stock is marked as non tracked, we can still add the product to the cart, even is the stock is not set higher than 0, but we can't add it from the wishlist.

I can do a simple PR is that 's a mistake

**Comment by rafalmal** [comment]
Disabling tracking means we always have enough products in stock. Stock value becomes irrelevant.

**Comment by t-n-y** [comment]
yes, this is why we should always add product to cart when it is not tracked. even if stock is set to 0 in admin

**Comment by rafalmal** [comment]
Sorry i missread this issue, but you propably using old version i just tested that and couldnt reproduce
![image](https://user-images.githubusercontent.com/105425505/235140795-d952447f-c60c-4893-bd8f-e6cb121c88fc.png)
![image](https://user-images.githubusercontent.com/105425505/235140892-95c7d80a-a0fe-403b-8198-3c48127f7961.png)

**Comment by t-n-y** [comment]
I am using the last version. But i am talking about adding products to the cart, from the wishlist

**Comment by rafalmal** [comment]
Oh i see this now, this bug exists in latest release but has been fixed allready and i could not recreate on master, we should add fixed release soon.

**Comment by roennow** [comment]
@rafalmal will a new release with a fix for this be released soon?
