### ISSUE TITLE
Symfony Toolbar problem on product page

### ISSUE THREAD

**Issue by DT-Tommy** [BitBagCommerce/SyliusWishlistPlugin#215]
Hi guys ,
I'm having a problem with the plugin on the product page. When I load the page, the Symfony toolbar never loads as in the attachment. Do you have any idea how to solve this problem?
Thank you 🙏 
![image](https://github.com/BitBagCommerce/SyliusWishlistPlugin/assets/140729625/71c43e2d-c8fb-4f1f-8cff-45e8dca7b539)

**Comment by senghe** [comment]
Hi @DT-Tommy, with no error message and any other information, I think we can't help you. But in meantime there was a few releases (including major one), so hopefully it should help you.

I'm closing the issue, please reopen it if it's still current.
