### ISSUE TITLE
Database Schema not in sync wit migrations

### ISSUE THREAD

**Issue by oliver-schulz** [BitBagCommerce/SyliusWishlistPlugin#222]
We are using Mysql and the DB Schema of this plugin is not in sync with the provided migrations. 

When you exec `bin/console do:mi:mi -n` the migration bundle will create a new migration file.

Please add the missing `token_idx` migration to this plugin.

**Comment by senghe** [comment]
Hi @oliver-schulz, thanks for the issue! :) I've prepared a PR for your idea. It passed the build, but I'm waiting currently for code review from our team, before it'll be merged.

Cheers! :)

**Comment by senghe** [comment]
It's merged :tada:

**Comment by oliver-schulz** [comment]
Also from my side, DB migration state is clean after plugin installation / update. Thx a lot!
