### ISSUE TITLE
Wishlist created on every request as anonymous user

### ISSUE THREAD

**Issue by oliver-schulz** [BitBagCommerce/SyliusWishlistPlugin#223]
In Version 4.0.1 with the Merge of the PR the bug where on every Request there is a new wishlist created.

After updating to 4.0.0 i created a test wich makes several request to sylius and counts the number of wishlists in database. Maybe also a good test for this plugin? 

Anyways, i think the Wishlist Resolver and the CreateWishList Command must be modified to also return null or at least not persisting to database. Evereytime when renering the add_item_to_cart form, it creates a wishlist in database.

**Comment by senghe** [comment]
Hi, this has been resolved in https://github.com/BitBagCommerce/SyliusWishlistPlugin/releases/tag/v4.0.2 :tada: 

Currently in 4.0.2 the wishlist is created only when reaching any /wishlist prefixed endpoint.

**Comment by oliver-schulz** [comment]
I can confirm, there is only a wishlist created when adding a product to it.
