### ISSUE TITLE
Variant pricing: Javascript JSON parse error in browser 

### ISSUE THREAD

**Issue by olimination** [BitBagCommerce/SyliusWishlistPlugin#225]
**Versions:**

- Sylius 1.12.11
- Sylius Wishlist Plugin 4.0.1

**Steps to reproduce:**

1. Open https://sylius-demo.bitbag.shop
2. Add some products to the wishlist
3. Open Wishlist: https://sylius-demo.bitbag.shop/wishlist
4. Check browser console and see the error "Uncaught SyntaxError: JSON.parse: expected ',' or ']' after array element at line 1 column 14 of the JSON data..."

Screenshot: 
![image](https://github.com/BitBagCommerce/SyliusWishlistPlugin/assets/662924/b0aa70c9-d41e-4f66-b53f-8b93440c0256)

**Possible fix:**
Tried to provide some fix here: https://github.com/BitBagCommerce/SyliusWishlistPlugin/pull/226

**Comment by senghe** [comment]
Hi @olimination, I've requested changes in your PR. Please call me, if you fix it.

**Comment by senghe** [comment]
I've already tested it on the plugin directly - it doesn't provide the errors as on our demo application. It can be result of not updated version of plugin there. I'm closing the issue now, but will fix the demo soon. Thanks! :)
