### ISSUE TITLE
AddToCartTypeExtension creates at least one Wishlist in DB

### ISSUE THREAD

**Issue by oliver-schulz** [BitBagCommerce/SyliusWishlistPlugin#232]
In `BitBag\SyliusWishlistPlugin\Form\Extension\AddToCartTypeExtension::buildForm()` there is a call to `resolveAndCreate()` which is not that good, because just hitting the product detail page writes data to DB :/

```
->add('wishlists', EntityType::class, [
    'class' => Wishlist::class,
    'choices' => $this->wishlistsResolver->resolveAndCreate(),
    'choice_label' => 'name',
    'mapped' => false,
])
```

Not sure what to do here jet, but maybe just call `$this->wishlistsResolver->resolve()` is also fine and we can live with a empty list of wishlists here?

**Comment by senghe** [comment]
Hi, unfortunately we can't change this behaviour, as the wishlists list is placed on product page (you can add product to a specified wishlist from this view). So we have to have at least one (default) wishlist during this request.

**Comment by oliver-schulz** [comment]
Imagine you have a high load on you ProductDetail Page an every Request writes something to your Database, do you think this is a good idea also? If you really need a default, why not resolving some empty object here which is not persisted to DB?
