### ISSUE TITLE
Unable to create wishlist using form submit in modal.

### ISSUE THREAD

**Issue by RickVdrongelen** [BitBagCommerce/SyliusWishlistPlugin#238]
When creating a wishlist using the modal, it sometimes happens that a user presses submits the form using the keyboard instead of pressing 'Perform' in the modal. 
Since the form in the modal does not have action or a submit event handler, the form posts its action to `/wishlist` instead of `/wishlist/create`. This causes either a `422 Method not allowed error`, but in most cases nothing happens.

Is there something i am missing or is this not yet implemented?

When it is not yet implemented, I believe this can fixed/implemented by doing the following.
Add either a action to the form in the modal to `/wishlists/create`. Or call the `performAction` javascript function when the form is submitted, instead of only handling the `performAction` function on the `click` event of the 'Perform' button.

Due to time constraints i am unable to submit a PR in the near future.

Thank for your time and this plugin.

**Comment by leszczuu** [comment]
should be fixed with https://github.com/BitBagCommerce/SyliusWishlistPlugin/pull/244
