### ISSUE TITLE
Unable to add translations to modal

### ISSUE THREAD

**Issue by RickVdrongelen** [BitBagCommerce/SyliusWishlistPlugin#239]
Hi all.

We are using the wishlist plugin in a different language, and we are able to override all translations that are used in the Twig templates, so that is great. But i am not able to easily change the content of the modal. And i believe all the text in this modal is all set in javascript. Is there an easy way to add the required translations instead of forking this repository?

Thanks for this plugin and your time.

**Comment by leszczuu** [comment]
should be fixed with, 
https://github.com/BitBagCommerce/SyliusWishlistPlugin/pull/244

translation / change of modal's content will be possible in 
https://github.com/BitBagCommerce/SyliusWishlistPlugin/pull/244/files#diff-2c5f7ef56a509f66f7a76dcaa1121d1b44887d054eb8667c34e507b6122ccee2R50
