### ISSUE TITLE
wishlist not updated after user register

### ISSUE THREAD

**Issue by t-n-y** [BitBagCommerce/SyliusWishlistPlugin#240]
When i come on the page as a new user, the wishlist is created without the shop user id. Then i create an account, an the wishlist is not updated, the shop user is not set

in [this issue](https://github.com/BitBagCommerce/SyliusWishlistPlugin/issues/132) there is the same behaviour, the field "shop_user_id" of the wishlist is not populated with the id of the user

**Comment by JanPalen** [comment]
Hi @t-n-y that issue is already solved. :white_check_mark:
