### ISSUE TITLE
Removing or adding to cart selected items broken when product's stock is 0

### ISSUE THREAD

**Issue by nixls** [BitBagCommerce/SyliusWishlistPlugin#248]
When trying to remove a product from wishlist using checkboxes and bulk actions while its stock is zero is not possible.
![image](https://github.com/BitBagCommerce/SyliusWishlistPlugin/assets/28026071/c171c9b5-317e-4745-9d36-2e3e533e690a)

Same thing happens when trying to add a product to cart using bulk actions while there is at least one item with 0 stock despite not being selected.

**Comment by tomkalon** [comment]
**Sprawdzono:**

First problem is already solved 👍 
Second problem is also solved 👍 

> When trying to add items from the wish list to the basket:
> - items that are available are added to the basket;
> 
> - for items that are out of stock, they remain on the wish list but are not added to the shopping basket - a flash message appears informing you that the item is out of stock.
