### ISSUE TITLE
Example _addToCart.html.twig adds product to cart instead of wishlist

### ISSUE THREAD

**Issue by TheDevilOnLine** [BitBagCommerce/SyliusWishlistPlugin#26]
The add to wishlist button in the example template supplied at /tests/Application/templates/ShopBundle/Product/Show/_addToCart.html.twig adds the product to the cart instead of the wishlist.

**Comment by bartektw** [comment]
Hi @TheDevilOnLine! Can you please give me more information about this issue? Which button are you talking about? Can you add a screenshot?
