### ISSUE TITLE
PHPStan

### ISSUE THREAD

**Issue by JakobTolkemit** [BitBagCommerce/SyliusWishlistPlugin#3]
Hey, I just ran phpstan on the code and it found 22 errors.
Thing is, we use a fork of this plugin in our project where we don't want any phpstan errors.
I could fix them in the fork, but pulling updates from this repository would probably bring them back.

**Comment by damonsson** [comment]
Thanks, @JakobTolkemit. So if you fix it in the fork, just do PR we'll accept it and everyone will be happy. And we will check code with phpstan before next future releases.
