### ISSUE TITLE
Fresh Install : miss "wishlist_cookie_token"

### ISSUE THREAD

**Issue by gponty** [BitBagCommerce/SyliusWishlistPlugin#36]
Hi,

I have an error message when i install plugin on fresh install :
"You have requested a non-existent parameter "wishlist_cookie_token"

Can you help me ?
Thank you

**Comment by pptasinski-bitbag** [comment]
Have you imported this file "@BitBagSyliusWishlistPlugin/Resources/config/config.yml" to Your _sylius.yaml file ?

**Comment by gponty** [comment]
You're right ! That's work !
But in the documentation, "composer require" is before import config.
Thank you

**Comment by pptasinski-bitbag** [comment]
Ohh sorry! We will change it. Thanks! 😄
