### ISSUE TITLE
SQL Migration from <1.5.x to >1.5.x

### ISSUE THREAD

**Issue by hdasdoria** [BitBagCommerce/SyliusWishlistPlugin#39]
Hello,

There's an issue with your Migration (`Version20201029161558.php`) while upgrading from version below 1.5 to version 1.5.x.

When executing `php bin/console doctrine:migration:migrate -q` it returns this error

```
Script doctrine:migration:migrate -q returned with error code 1
!!  
!!  In AbstractMySQLDriver.php line 57:
!!                                                                                 
!!    An exception occurred while executing 'CREATE TABLE bitbag_wishlist (id INT  
!!     AUTO_INCREMENT NOT NULL, shop_user_id INT DEFAULT NULL, token VARCHAR(255)  
!!     NOT NULL, UNIQUE INDEX UNIQ_578D4E775F37A13B (token), UNIQUE INDEX UNIQ_57  
!!    8D4E77A45D93BF (shop_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8   
!!    COLLATE `UTF8_unicode_ci` ENGINE = InnoDB':                                  
!!                                                                                 
!!    SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'bitbag_wish  
!!    list' already exists                                                         
!!                                                                                 
!!  
!!  In Exception.php line 18:
!!                                                                                 
!!    SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'bitbag_wish  
!!    list' already exists                                                         
!!                                                                                 
!!  
!!  In PDOConnection.php line 52:
!!                                                                                 
!!    SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'bitbag_wish  
!!    list' already exists                                                         
!!                                                                                 
!!  
!!  doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CONFIGURATION] [--db-configuration DB-CONFIGURATION] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]
!!  
!!  
```

It is actually because you don't check tables and columns in your migration class with methods like `$schema->hasTable('xxx')` or `$schema->getTable('xxx')->hasColumn('xxx')`.

Thx

**Comment by hdasdoria** [comment]
For now, the only solution we had is to set the migration as executed directly in the database:

`INSERT INTO doctrine_migration_versions (version, executed_at, execution_time) VALUES('BitBag\\SyliusWishlistPlugin\\Migrations\\Version20201029161558', '2020-09-15 09:59:45.000', 1)`

**Comment by tifed** [comment]
> For now, the only solution we had is to set the migration as executed directly in the database:
> 
> `INSERT INTO doctrine_migration_versions (version, executed_at, execution_time) VALUES('BitBag\\SyliusWishlistPlugin\\Migrations\\Version20201029161558', '2020-09-15 09:59:45.000', 1)`

```
php bin/console doctrine:migrations:version BitBag\\SyliusWishlistPlugin\\Migrations\\Version20201029161558 --add --no-interaction
```

**Comment by crackgm** [comment]
> > For now, the only solution we had is to set the migration as executed directly in the database:
> > `INSERT INTO doctrine_migration_versions (version, executed_at, execution_time) VALUES('BitBag\\SyliusWishlistPlugin\\Migrations\\Version20201029161558', '2020-09-15 09:59:45.000', 1)`
> 
> ```
> php bin/console doctrine:migrations:version BitBag\\SyliusWishlistPlugin\\Migrations\\Version20201029161558 --add --no-interaction
> ```

Please use @tifed solution to fix this issue.
