### ISSUE TITLE
Doctrine migration is not up to date with the entity mappings

### ISSUE THREAD

**Issue by piotrkardasz** [BitBagCommerce/SyliusWishlistPlugin#55]
After migrating migration `BitBag\SyliusWishlistPlugin\Migrations\Version20201029161558` 
and checking schema by following commad
```bash
bin/console doctrine:schema:validate
```
It will return an error
```text
[ERROR] The database schema is not in sync with the current mapping file.
```
and after checking for missing SQL queries
```bash
bin/console doctrine:schema:update --dump-sql
```
returns:
```
 The following SQL statements will be executed:

     ALTER TABLE bitbag_wishlist_product DROP FOREIGN KEY FK_3DBE67A0FB8E54CD;
     ALTER TABLE bitbag_wishlist_product ADD CONSTRAINT FK_3DBE67A0FB8E54CD FOREIGN KEY (wishlist_id) REFERENCES bitbag_wishlist (id) ON DELETE CASCADE;
```
The next migration file should be created?

**Comment by stefantalen** [comment]
@pptasinski-bitbag Can you please tag this release with a version?

I'm also confused by the `@deprecated` PHPDoc usage in the migrations, why bother with the migrations if they are being deprecated in v2.0 of this plugin?

**Comment by pptasinski-bitbag** [comment]
@stefantalen  it is in 1.5.4 version.

**Comment by pptasinski-bitbag** [comment]
We are preparing integration with API platform now so we will create new release soon (1.5.5) 👌

Regarding migrations, from version 2.0 of this plugin we will not use migrations at all that's why now we've marked them as deprecated.

**Comment by stefantalen** [comment]
Thanks for the quick response!

I'll just have it update to `dev-master as 1.5.4.1` until 1.5.5 gets released so I don't have an extra migration.

Too bad about deprecating migrations, having them namespaced (As of `doctrine/migrations:3.0`) makes updating a lot easier since you don't have to create migrations for code you don't write.
