### ISSUE TITLE
Remove redundant condition

### ISSUE THREAD

**Issue by delyro** [BitBagCommerce/SyliusWishlistPlugin#57]
See line: 

https://github.com/BitBagCommerce/SyliusWishlistPlugin/blob/master/src/EventListener/MergeUserWishlistItemsListener.php#L73

Previously, we check in line 67 if $cookieWishlist is null, therefore we don't need to check that again in line 73 and 79 since we used return statement.

**Comment by tgrochowski** [comment]
That is already resolved in latest version, thanks for pointing that out
