### ISSUE TITLE
SyliusWishlistPlugin has a dependency on a non-existent service "templating.engine.twig".                                                                           !!            

### ISSUE THREAD

**Issue by bellu** [BitBagCommerce/SyliusWishlistPlugin#62]
PHP: 7.3.29
Sylius: 1.9.5
Symfony: 5.3.3

Hi,
after launching ` composer require bitbag/wishlist-plugin`, i got this error:

_The service "bitbag_sylius_wishlist_plugin.controller.action.list_wishlist_products" has a dependency on a non-existent service "templating.engine.twig"._

Any suggest?

Thanks

**Comment by tgrochowski** [comment]
Thanks for submitting an issue. The newest version of the plugin shouldn't have this issue so I strongly encourage to update it in Your project :slightly_smiling_face: 
https://github.com/BitBagCommerce/SyliusWishlistPlugin/releases/tag/v1.6.0

If You need older version for any reason, You could try to override this service and replace `@templating.engine.twig` with `@twig` like said in [Sylius upgrade notes here](https://github.com/Sylius/Sylius/blob/master/UPGRADE-1.9.md#upgrades-symfony-to-v52)

**Comment by tgrochowski** [comment]
@bellu Have You managed to resolve this issue ?

**Comment by bellu** [comment]
@tgrochowski Yes, after updating to 1.6 everything is working.
Thanks for the support
