### ISSUE TITLE
[Q&A] The cookie name cannot be empty

### ISSUE THREAD

**Issue by igormukhingmailcom** [BitBagCommerce/SyliusWishlistPlugin#65]
This can happen after logging in to Account area 
when you set something like this at plugin's config:

```yaml
bit_bag_sylius_wishlist:
    wishlist_cookie_token: false
```

(I've misunderstood purpose of `wishlist_cookie_token` option and set false there)...

**Comment by pitosik** [comment]
Hello, issue has been resolved in #95 - closing.
