### ISSUE TITLE
Indentation broken at getConfigTreeBuilder

### ISSUE THREAD

**Issue by igormukhingmailcom** [BitBagCommerce/SyliusWishlistPlugin#67]

**Comment by TymekB** [comment]
Can you provide more detailed information about the issue?

**Comment by igormukhingmailcom** [comment]
Sure:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/6544038/128403598-4ad61936-f325-43a4-b37d-4038939fe81c.png">

**Comment by pitosik** [comment]
Hello, issue is resolved in #88.
